### ISSUE TITLE
Fine tuning of two seperate layers in a model

### ISSUE THREAD

**Issue by VanitarNordic** [flyyufelix/cnn_finetune#11]
Hello, I read your blog post about fine-tuning. very good explanation. I have an issue with a model, which could be interesting to investigate. Please have a look:

https://github.com/nicolov/segmentation_keras/blob/master/model.py

I want to fine-tune this with a different number of classes (for example 2).

By the way I should modify these two layers and change `21` to `2`:

`model.add(Convolution2D(21, 1, 1, activation='linear', name='fc-final'))`

and 

`model.add(Convolution2D(21, 1, 1, name='ct_final'))`

Also, freeze other layers and make them `trainable = False`

Now my questions:

1. I don't know how can I determine how many layers model have to freeze until one of these layers.

2. I should freeze except than two separate layers. if the correct method of freezing in such situations is to do separately, I should know what is the number of these layers in the model. How can I know that?

**Comment by flyyufelix** [comment]
Glad to hear that my blog post helps :)

To answer your question, I think it's really more of an art than science to determine the the number of layers to freeze. Since the first few layers encapsulate low level concepts such as lines and curves that can be re-used in other problems, we normally freeze those layers. Freezing layers can also speed up training. So it's a hyper-parameter you have to determine. 

To know the number of layers in the model, you can do len(model.layers)

**Comment by VanitarNordic** [comment]
Thank you very much. Do you have any suggestion about fine-tuning models such as this one? two layers makes it tricky for me and I found no example for this in the internet. This could be an interesting topic for the blog either.

**Comment by flyyufelix** [comment]
The same principle for fine-tuning one layer can be applied to fine-tuning multiple layers. You replace the two layers with your own layers (from 21 classes to 2 classes) and run fit(). I don't see how having 2 layers would affect the fine-tuning procedure.

**Comment by VanitarNordic** [comment]
I should not freeze the weights before these layers as you did? This makes it tricky for me.

**Comment by flyyufelix** [comment]
You can just freeze the weights for the first few convolutional layers for VGG16, keep other layers trainable
