### ISSUE TITLE
Is this step necessary for ( does you example for vgg16/dataset_cifar50 do this step)?

### ISSUE THREAD

**Issue by MinmingQian** [flyyufelix/cnn_finetune#18]
```
# For Tensorflow 
# Switch RGB to BGR order 
x = x[:, :, :, ::-1]  

# Subtract ImageNet mean pixel 
x[:, :, :, 0] -= 103.939
x[:, :, :, 1] -= 116.779
x[:, :, :, 2] -= 123.68

# For Theano
# Switch RGB to BGR order 
x = x[:, ::-1, :, :]

# Subtract ImageNet mean pixel 
x[:, 0, :, :] -= 103.939
x[:, 1, :, :] -= 116.779
x[:, 2, :, :] -= 123.68
```

I didn't do this step because I did not see your code for vgg 16 do this?
The problem is why we need to do, will the pixel value turn into negatvie if we minus the mean pixel of ImageNet?

**Comment by yxc1234567539** [comment]
I also have this problem,I didn't find subtracting mean pixel in the code.but the result is good.

**Comment by flyyufelix** [comment]
The pre-trained weights were computed with the mean pixel subtraction preprocessing step. Subtraction mean pixel (i.e. normalising inputs) is common practice to facilitate and to stabilise training. So theoretically speaking in order to get the best out of the pre-trained weights you should follow the same preprocessing procedure. However, in practice, slight deviation in the preprocessing step (e.g. minus another set of mean pixels) have minimal effect to performance. But I wouldn't go as far as feeding raw pixel to the network directly.
